### ISSUE TITLE
License

### ISSUE THREAD

**Issue by palmskog** [kth-step/abs-metatheory#16]
Since we now have some probably-useful code, it's a good idea to choose a license and add a `LICENSE` file. This ensures the code can be reused in other projects more easily, which I think is a good idea.

@Aqissiaq my default license is the [MIT license](https://choosealicense.com/licenses/mit/), as explained [here](https://github.com/coq-community/manifesto?tab=readme-ov-file#best-practices). What do you think?

**Comment by Aqissiaq** [comment]
I also default to MIT, so that sounds good to me.
